# Generated by Django 5.0 on 2024-09-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mod", models.CharField(max_length=300)),
                ("cena", models.IntegerField()),
                ("nomer", models.CharField(max_length=6)),
            ],
        ),
    ]
